# Generated by Django 4.1.2 on 2022-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='Дата создания',
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Дата последнего обновления',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('hidden', 'Hidden'),
                            ('published', 'Published'),
                        ],
                        db_index=True,
                        default='published',
                        max_length=10,
                        verbose_name='Статус',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=250, verbose_name='Заголовок'),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='Дата создания',
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Дата последнего обновления',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('hidden', 'Hidden'),
                            ('published', 'Published'),
                        ],
                        db_index=True,
                        default='published',
                        max_length=10,
                        verbose_name='Статус',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created',),
            },
        ),
    ]
