# Generated by Django 4.1.2 on 2022-12-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='post_comments',
                related_query_name='obj',
                to='blog.post',
                verbose_name='Пост',
            ),
        ),
    ]
