# Generated by Django 4.1.2 on 2022-12-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_image_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                upload_to="images/", verbose_name="Изображение"
            ),
        ),
    ]
