# Generated by Django 4.1.2 on 2022-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_verified_user_verification_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активация"),
        ),
    ]
